// NOTE(smoke): os_input_xkey_to_key is too messy
// so it's a separate file, other platform backends
// don't need this

#include "os_xlib.h"

// NOTE(smoke): generated by ChatGPT
OS_InputKey os_input_xkey_to_key(XKeyEvent *event)
{
    KeySym sym = XLookupKeysym(event, 0);
    
    switch (sym)
    {
        // Letters
        case XK_a: case XK_A: return OS_KEY_A;
        case XK_b: case XK_B: return OS_KEY_B;
        case XK_c: case XK_C: return OS_KEY_C;
        case XK_d: case XK_D: return OS_KEY_D;
        case XK_e: case XK_E: return OS_KEY_E;
        case XK_f: case XK_F: return OS_KEY_F;
        case XK_g: case XK_G: return OS_KEY_G;
        case XK_h: case XK_H: return OS_KEY_H;
        case XK_i: case XK_I: return OS_KEY_I;
        case XK_j: case XK_J: return OS_KEY_J;
        case XK_k: case XK_K: return OS_KEY_K;
        case XK_l: case XK_L: return OS_KEY_L;
        case XK_m: case XK_M: return OS_KEY_M;
        case XK_n: case XK_N: return OS_KEY_N;
        case XK_o: case XK_O: return OS_KEY_O;
        case XK_p: case XK_P: return OS_KEY_P;
        case XK_q: case XK_Q: return OS_KEY_Q;
        case XK_r: case XK_R: return OS_KEY_R;
        case XK_s: case XK_S: return OS_KEY_S;
        case XK_t: case XK_T: return OS_KEY_T;
        case XK_u: case XK_U: return OS_KEY_U;
        case XK_v: case XK_V: return OS_KEY_V;
        case XK_w: case XK_W: return OS_KEY_W;
        case XK_x: case XK_X: return OS_KEY_X;
        case XK_y: case XK_Y: return OS_KEY_Y;
        case XK_z: case XK_Z: return OS_KEY_Z;
        
        // Digits
        case XK_0: return OS_KEY_0;
        case XK_1: return OS_KEY_1;
        case XK_2: return OS_KEY_2;
        case XK_3: return OS_KEY_3;
        case XK_4: return OS_KEY_4;
        case XK_5: return OS_KEY_5;
        case XK_6: return OS_KEY_6;
        case XK_7: return OS_KEY_7;
        case XK_8: return OS_KEY_8;
        case XK_9: return OS_KEY_9;
        
        // Function keys
        case XK_F1:  return OS_KEY_F1;
        case XK_F2:  return OS_KEY_F2;
        case XK_F3:  return OS_KEY_F3;
        case XK_F4:  return OS_KEY_F4;
        case XK_F5:  return OS_KEY_F5;
        case XK_F6:  return OS_KEY_F6;
        case XK_F7:  return OS_KEY_F7;
        case XK_F8:  return OS_KEY_F8;
        case XK_F9:  return OS_KEY_F9;
        case XK_F10: return OS_KEY_F10;
        case XK_F11: return OS_KEY_F11;
        case XK_F12: return OS_KEY_F12;
        
        // Navigation keys
        case XK_Left:  return OS_KEY_LEFT;
        case XK_Right: return OS_KEY_RIGHT;
        case XK_Up:    return OS_KEY_UP;
        case XK_Down:  return OS_KEY_DOWN;
        case XK_Home:  return OS_KEY_HOME;
        case XK_End:   return OS_KEY_END;
        case XK_Page_Up:   return OS_KEY_PAGE_UP;
        case XK_Page_Down: return OS_KEY_PAGE_DOWN;
        case XK_Insert: return OS_KEY_INSERT;
        case XK_Delete: return OS_KEY_DELETE;
        
        // Control keys
        case XK_Shift_L:    return OS_KEY_LSHIFT;
        case XK_Shift_R:    return OS_KEY_RSHIFT;
        case XK_Control_L:  return OS_KEY_LCONTROL;
        case XK_Control_R:  return OS_KEY_RCONTROL;
        case XK_Alt_L:      return OS_KEY_LALT;
        case XK_Alt_R:      return OS_KEY_RALT;
        case XK_Super_L:    return OS_KEY_LSUPER;
        case XK_Super_R:    return OS_KEY_RSUPER;
        case XK_Escape:     return OS_KEY_ESCAPE;
        case XK_Tab:        return OS_KEY_TAB;
        case XK_Return:     return OS_KEY_ENTER;
        case XK_BackSpace:  return OS_KEY_BACKSPACE;
        case XK_space:      return OS_KEY_SPACE;
        
        // Symbols
        case XK_comma:       return OS_KEY_COMMA;
        case XK_period:      return OS_KEY_PERIOD;
        case XK_minus:       return OS_KEY_MINUS;
        case XK_equal:       return OS_KEY_EQUAL;
        case XK_semicolon:   return OS_KEY_SEMICOLON;
        case XK_apostrophe:  return OS_KEY_APOSTROPHE;
        case XK_grave:       return OS_KEY_GRAVE;
        case XK_slash:       return OS_KEY_SLASH;
        case XK_backslash:   return OS_KEY_BACKSLASH;
        case XK_bracketleft: return OS_KEY_LBRACKET;
        case XK_bracketright:return OS_KEY_RBRACKET;
        
        default:
        return OS_MAX_KEYS; // Unknown / unmapped
    }
}
